Tyrannosaurus/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tyrannosaurus.UI.Controllers
{
    public class HomeController : Controller
    {
        public ViewResult Index()
        {
            ViewBag.Message = "Observation logging tool for people with Tyrosinemia.";

            return View();
        }

        public ViewResult About()
        {
            ViewBag.Message = "";

            return View();
        }

        public ViewResult Contact()
        {
            ViewBag.Message = "";

            return View();
        }
    }
}

Tyrannosaurus/Controllers/ObservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tyrannosaurus.Core.Domain;
using Tyrannosaurus.UI.Models;
using AutoMapper;
using Tyrannosaurus.UI.Services;

namespace Tyrannosaurus.UI.Controllers
{
    public class ObservationsController : Controller
    {

        //         private TyrannosaurusEntities db = new TyrannosaurusEntities();

        private IObservationService service;

        public ObservationsController(IObservationService service)
        {
            this.service = service;
        }

        //
        // GET: /Observations/

        public ActionResult Index()
        {
            return View();
        }

        //
        // POST: /Observations/GetObservations/

        public PartialViewResult GetObservations(string mode = "charts")
        {

            // var observations = db.Observations.Include(o => o.Observee);

            // FIXME: Hard coded ID value
            var observations = this.service.GetObservationsByObserveeId(1);

            Mapper.CreateMap<Observation, ObservationsList>();

            var observationList = Mapper.Map<IList<Observation>, IList<ObservationsList>>(observations);

            return PartialView(mode == "grid" ? "_ObservationGrid" : "_ObservationChart", observationList);
        }

        //
        // GET: /Observations/Create

        public ViewResult Create()
        {
            var observation = new Observation()
                {   
                    ObservationDate = DateTime.Now
                };

            return View(new ObservationFormViewModel(observation));
        }

        //
        // POST: /Observations/Create

        [HttpPost]
        public ActionResult Create(Observation observation)
        {
            if (ModelState.IsValid)
            {
                this.service.AddObservation(observation);

                return RedirectToAction("Details", new { id = observation.ObservationId });
            }

            return View(new ObservationFormViewModel(observation));
        }

        //
        // GET: /Observations/Detail

        [HttpGet]
        public ActionResult Details(int id = 0)
        {
            var observation = this.service.GetObservation(id);

            // Observation observation = db.Observations.Find(id);

            if (observation == null)
            {
                return HttpNotFound();
            }
            return View(observation);   
        }
    
        //
        // GET: /Observations/Edit

        public ActionResult Edit(int id = 0)
        {
            // Observation observation = db.Observations.Find(id);

            var observation = this.service.GetObservation(id);

            if (observation == null)
            {
                return HttpNotFound();
            }
            return View(new ObservationFormViewModel(observation));
        }

        //
        // POST: /Observations/Edit

        [HttpPost]
        public ActionResult Edit(Observation observation)
        {
            if (ModelState.IsValid)
            {
                this.service.EditObservation(observation);

                return RedirectToAction("Details",new {id = observation.ObservationId});
            }

            return View(new ObservationFormViewModel(observation));
        }

        protected override void Dispose(bool disposing)
        {
            this.service.Dispose();
            base.Dispose(disposing);
        }
    }
}

Tyrannosaurus/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        This website is to help record and review the various observations made for the metabolic condition Tyrosinemia.
    </p>
</article>

<aside>
    <h3>References</h3>
    <p>
        Here are some links to information about Tyrosinemia Type I
    </p>
    <ul>
        <li><a href="http://en.wikipedia.org/wiki/Type_I_tyrosinemia">Wikipedia</a></li>
        <li><a href="http://ghr.nlm.nih.gov/condition/tyrosinemia">National Library of Medicine (US)</a></li>
        
        
    </ul>
</aside>

Tyrannosaurus/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

@*<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>*@

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:jadgoss@hotmail.com">jadgoss@hotmail.com</a></span>
    </p>
@*    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>*@
</section>

@*<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>*@

Tyrannosaurus/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Tyrannosaurus";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
                <p><h2>@ViewBag.Message</h2></p>
            </hgroup>
        </div>
    </section>
}
<h3>Get started:</h3>
<ul>
    <li>@Html.ActionLink("View past observations","Index","Observations")</li>
    <li>@Html.ActionLink("Add a new observation","Create","Observations")</li>
</ul>